## Model ##
name: "ResNet18_WS_LPT2"
pretrained: False
l2_norm: False
use_bn_layer: False
# freeze_layer: False  # or ['fc']
last_feature_dim: 512
rho: 1e-3
init_mode: "kaiming_normal"

moving_average: False
mv_alpha: 0.9
ma_start: 1

blk1_uni_quant: True
blk_start_uni_quant: True
blk_end_uni_quant: True
conv1_uni_quant: True
conv2_uni_quant: True
downsample_uni_quant: True