## Model ##
name: "ResNet18_WS_LPT2"
pretrained: False
l2_norm: False
use_bn_layer: False
# freeze_layer: False  # or ['fc']
last_feature_dim: 512
rho: 1e-3
init_mode: "kaiming_uniform"

moving_average: False
mv_alpha: 0.9
ma_start: 1