### dataset ###
name: 'CIFAR100'
path: './data'
client_path: "./client_data"
num_instances: 0
download: True
# cutmix param.
cutmix:
  use: False
  num_mix: 2
  beta: 1
  prob: 0.5
  cutmix_reg: False