### dataset ###
name: 'TinyImageNet'
path: './data'
client_path: "./client_data"
num_instances: 0
download: False # place TinyImageNet dataset to the above path
# cutmix param.
cutmix:
  use: False
  num_mix: 2
  beta: 1
  prob: 0.5
  cutmix_reg: False