name: 'none'
LPT_name: "LPT"
uplink: False
downlink: False

# WSQ
keyword: []
wt_bit: 8
wt_clip_prob: -1
momentum: 0.1

# LPT
quant: True
quant_type: 'stochastic'
quantization_bits: 6
small_block: 'None'
block_dim: 'B'

weight_uniform_mode: 'BFP'
grad_uniform_mode: 'BFP'
act_uniform_mode: 'occ'

weight_quantization: True
gradient_quantization: True
activation_quantization: True

lut_mode: 'E3M2'    # E2M3, E3M2, E1M4
comp: True